package mcpserver

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/soggycactus/paprika-3-mcp/internal/database"
	"github.com/soggycactus/paprika-3-mcp/internal/paprika"
)

type NewServerOptions struct {
	Version  string
	Username string
	Password string
	Paprika  *paprika.Client
	Logger   *slog.Logger
}

func NewServer(opts NewServerOptions) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger)
	if err != nil {
		return nil, err
	}

	// Initialize local database
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get user home directory: %w", err)
	}
	dbPath := filepath.Join(homeDir, ".paprika-3-mcp", "recipes.db")

	db, err := database.NewRecipeDB(dbPath, opts.Logger)
	if err != nil {
		return nil, fmt.Errorf("failed to initialize database: %w", err)
	}

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3: paprika3,
		db:       db,
		server:   s,
		logger:   opts.Logger,
	}, nil
}

type Server struct {
	paprika3 *paprika.Client
	db       *database.RecipeDB
	logger   *slog.Logger
	server   *server.MCPServer
}

func (s *Server) Start() {
	go s.updateResources()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app"),
		mcp.WithString("uid", mcp.Description("The UID of the recipe"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.Required()),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.Required()),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.Required()),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.Required()),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.Required()),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.Required()),
	)
	getAllRecipesTool := mcp.NewTool("get_all_paprika_recipes",
		mcp.WithDescription("Retrieve all recipes from the Paprika 3 app. Can optionally filter by name or limit the number of results. Uses local database for faster access."),
		mcp.WithString("name_filter", mcp.Description("Optional: Filter recipes by name (case-insensitive partial match)"), mcp.DefaultString("")),
		mcp.WithNumber("limit", mcp.Description("Optional: Maximum number of recipes to return (0 = no limit)"), mcp.DefaultNumber(0)),
		mcp.WithNumber("offset", mcp.Description("Optional: Number of recipes to skip (for pagination)"), mcp.DefaultNumber(0)),
		mcp.WithBoolean("force_sync", mcp.Description("Optional: Force sync from Paprika API before retrieving (slower but ensures latest data)"), mcp.DefaultBool(false)),
	)
	syncRecipesTool := mcp.NewTool("sync_paprika_recipes",
		mcp.WithDescription("Sync all recipes from Paprika 3 cloud to local database. This improves performance for future queries."),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	}, server.ServerTool{
		Tool:    getAllRecipesTool,
		Handler: s.getAllRecipes,
	}, server.ServerTool{
		Tool:    syncRecipesTool,
		Handler: s.syncRecipes,
	})

	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("Server error", "err", err)
	}
}

func (s *Server) updateResources() {
	s.addResources()

	ticker := time.NewTicker(1 * time.Minute)
	for range ticker.C {
		s.addResources()
	}
}

func (s *Server) addResources() {
	s.logger.Info("Updating recipe resources")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// List all recipes to expose them as resources
	recipes, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list paprika recipes", "err", err)
		return
	}

	if len(recipes.Result) >= 10 {
		s.logger.Info("adding recipes resources concurrently")
		s.addResourcesConcurrently(recipes)
		return
	}

	for _, r := range recipes.Result {
		if err := s.addRecipeResource(r.UID); err != nil {
			s.logger.Error("failed to add recipe as MCP resource", "err", err)
		}
	}
}

func (s *Server) addRecipeResource(uid string) error {
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return err
	}

	if recipe.InTrash {
		return nil
	}

	resourceContents := mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}

	s.server.AddResource(mcp.NewResource(fmt.Sprintf("paprika://recipes/%s", recipe.UID), recipe.Name, mcp.WithResourceDescription(recipe.ResourceDescription()), mcp.WithMIMEType("text/markdown")), func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
		return []mcp.ResourceContents{resourceContents}, nil
	})

	duration := time.Since(start)
	s.logger.Info("Added resource", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return nil
}

func (s *Server) addResourcesConcurrently(recipes *paprika.RecipeList) {
	buffer := make(chan struct{}, 10)

	for _, r := range recipes.Result {
		go func() (err error) {
			buffer <- struct{}{}
			defer func() {
				<-buffer
			}()

			defer func(err error) {
				if err != nil {
					s.logger.Error("failed to add recipe as MCP resource", "err", err)
				}
			}(err)

			return s.addRecipeResource(r.UID)
		}()
	}
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	servings := req.Params.Arguments["servings"].(string)
	prepTime := req.Params.Arguments["prep_time"].(string)
	cookTime := req.Params.Arguments["cook_time"].(string)
	description := req.Params.Arguments["description"].(string)
	notes := req.Params.Arguments["notes"].(string)
	difficulty := req.Params.Arguments["difficulty"].(string)

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, ok := req.Params.Arguments["uid"].(string)
	if !ok || len(uid) == 0 {
		return nil, errors.New("uid is required")
	}
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	description, ok := req.Params.Arguments["description"].(string)
	if !ok {
		return nil, errors.New("description is required")
	}
	servings, ok := req.Params.Arguments["servings"].(string)
	if !ok {
		return nil, errors.New("servings is required")
	}
	prepTime, ok := req.Params.Arguments["prep_time"].(string)
	if !ok {
		return nil, errors.New("prepTime is required")
	}
	cookTime, ok := req.Params.Arguments["cook_time"].(string)
	if !ok {
		return nil, errors.New("cookTime is required")
	}
	notes, ok := req.Params.Arguments["notes"].(string)
	if !ok {
		return nil, errors.New("notes is required")
	}
	difficulty, ok := req.Params.Arguments["difficulty"].(string)
	if !ok {
		return nil, errors.New("difficulty is required")
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		UID:         uid,
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) getAllRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Parse optional parameters
	nameFilter := ""
	if nf, ok := req.Params.Arguments["name_filter"].(string); ok {
		nameFilter = nf
	}

	limit := 0
	if l, ok := req.Params.Arguments["limit"].(float64); ok {
		limit = int(l)
	}

	offset := 0
	if o, ok := req.Params.Arguments["offset"].(float64); ok {
		offset = int(o)
	}

	forceSync := false
	if fs, ok := req.Params.Arguments["force_sync"].(bool); ok {
		forceSync = fs
	}

	// If force_sync is true, sync from Paprika first
	if forceSync {
		s.logger.Info("Force sync requested, syncing from Paprika API")
		if _, err := s.syncRecipes(ctx, mcp.CallToolRequest{}); err != nil {
			s.logger.Error("failed to sync recipes", "error", err)
			return nil, fmt.Errorf("failed to sync recipes: %w", err)
		}
	}

	// Try to get from local database first
	recipes, totalCount, err := s.db.GetAllRecipes(nameFilter, limit, offset)
	if err != nil {
		s.logger.Error("failed to get recipes from database", "error", err)
		return nil, fmt.Errorf("failed to get recipes from database: %w", err)
	}

	// Build markdown output with all recipes
	var output string
	if nameFilter != "" {
		output += fmt.Sprintf("# Filtered Paprika Recipes (%d of %d recipes)\n", len(recipes), totalCount)
	} else {
		output += fmt.Sprintf("# Paprika Recipes (%d recipes", len(recipes))
		if offset > 0 || limit > 0 {
			output += fmt.Sprintf(", showing %d-%d of %d", offset+1, offset+len(recipes), totalCount)
		}
		output += ")\n"
	}
	output += "\n**Source:** Local Database\n"

	lastSync, _ := s.db.GetSyncMetadata("last_sync_time")
	if lastSync != "" {
		output += fmt.Sprintf("**Last Synced:** %s\n", lastSync)
	}
	output += "\n"

	for _, recipe := range recipes {
		output += "---\n\n"
		output += recipe.ToMarkdown()
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved recipes from database", "returned", len(recipes), "total", totalCount, "duration", duration)

	return mcp.NewToolResultText(output), nil
}

func (s *Server) syncRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	ctx, cancel := context.WithTimeout(ctx, 120*time.Second)
	defer cancel()

	s.logger.Info("Starting recipe sync from Paprika API")

	// Get the list of recipe UIDs
	recipeList, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list recipes", "error", err)
		return nil, err
	}

	s.logger.Info("Syncing recipes", "count", len(recipeList.Result))

	// Fetch all recipes concurrently
	type recipeResult struct {
		recipe *paprika.Recipe
		err    error
	}

	results := make(chan recipeResult, len(recipeList.Result))
	semaphore := make(chan struct{}, 10) // Limit concurrent requests

	for _, r := range recipeList.Result {
		go func(uid string) {
			semaphore <- struct{}{}
			defer func() { <-semaphore }()

			recipe, err := s.paprika3.GetRecipe(ctx, uid)
			results <- recipeResult{recipe: recipe, err: err}
		}(r.UID)
	}

	// Collect results and save to database
	var syncedCount int
	var errorCount int
	for i := 0; i < len(recipeList.Result); i++ {
		result := <-results
		if result.err != nil {
			s.logger.Error("failed to fetch recipe", "error", result.err)
			errorCount++
			continue
		}

		// Save to database
		if err := s.db.UpsertRecipe(result.recipe); err != nil {
			s.logger.Error("failed to save recipe to database", "error", err, "recipe", result.recipe.Name)
			errorCount++
			continue
		}
		syncedCount++
	}

	// Update sync metadata
	syncTime := time.Now().Format(time.RFC3339)
	if err := s.db.SetSyncMetadata("last_sync_time", syncTime); err != nil {
		s.logger.Error("failed to set sync metadata", "error", err)
	}

	duration := time.Since(start)
	s.logger.Info("Sync completed", "synced", syncedCount, "errors", errorCount, "duration", duration)

	output := fmt.Sprintf("# Recipe Sync Complete\n\n")
	output += fmt.Sprintf("- **Total recipes synced:** %d\n", syncedCount)
	output += fmt.Sprintf("- **Errors:** %d\n", errorCount)
	output += fmt.Sprintf("- **Duration:** %s\n", duration)
	output += fmt.Sprintf("- **Sync time:** %s\n", syncTime)

	return mcp.NewToolResultText(output), nil
}

// contains performs a case-insensitive substring match
func contains(s, substr string) bool {
	s, substr = toLower(s), toLower(substr)
	return len(s) >= len(substr) && (s == substr || indexOfSubstr(s, substr) >= 0)
}

func toLower(s string) string {
	result := make([]rune, len(s))
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			result[i] = r + 32
		} else {
			result[i] = r
		}
	}
	return string(result)
}

func indexOfSubstr(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
