package mcpserver

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/soggycactus/paprika-3-mcp/internal/database"
	"github.com/soggycactus/paprika-3-mcp/internal/paprika"
)

type NewServerOptions struct {
	Version  string
	Username string
	Password string
	Paprika  *paprika.Client
	Logger   *slog.Logger
}

func NewServer(opts NewServerOptions) (*Server, error) {
	paprika3, err := paprika.NewClient(opts.Username, opts.Password, opts.Version, opts.Logger)
	if err != nil {
		return nil, err
	}

	// Connect to Paprika's local database
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get user home directory: %w", err)
	}
	dbPath := filepath.Join(homeDir, `AppData\Local\Paprika Recipe Manager 3\Database\Paprika.sqlite`)

	db, err := database.NewRecipeDB(dbPath, opts.Logger)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to Paprika database: %w", err)
	}

	s := server.NewMCPServer("paprika-3-mcp", opts.Version, server.WithResourceCapabilities(false, false))
	return &Server{
		paprika3: paprika3,
		db:       db,
		server:   s,
		logger:   opts.Logger,
	}, nil
}

type Server struct {
	paprika3 *paprika.Client
	db       *database.RecipeDB
	logger   *slog.Logger
	server   *server.MCPServer
}

func (s *Server) Start() {
	go s.updateResources()

	createRecipeTool := mcp.NewTool("create_paprika_recipe",
		mcp.WithDescription("Save new recipes generated by LLMs in the Paprika 3 app"),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.DefaultString("")),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.DefaultString("")),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.DefaultString("")),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.DefaultString("")),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.DefaultString("")),
	)
	updateRecipeTool := mcp.NewTool("update_paprika_recipe",
		mcp.WithDescription("Update existing recipes in the Paprika 3 app"),
		mcp.WithString("uid", mcp.Description("The UID of the recipe"), mcp.Required()),
		mcp.WithString("name", mcp.Description("The name of the recipe"), mcp.Required()),
		mcp.WithString("ingredients", mcp.Description("The ingredients of the recipe"), mcp.Required()),
		mcp.WithString("directions", mcp.Description("The directions for the recipe"), mcp.Required()),
		mcp.WithString("description", mcp.Description("The description of the recipe"), mcp.Required()),
		mcp.WithString("notes", mcp.Description("The notes for the recipe"), mcp.Required()),
		mcp.WithString("servings", mcp.Description("The number of servings for the recipe"), mcp.Required()),
		mcp.WithString("prep_time", mcp.Description("The prep time for the recipe"), mcp.Required()),
		mcp.WithString("cook_time", mcp.Description("The cook time for the recipe"), mcp.Required()),
		mcp.WithString("difficulty", mcp.Description("The difficulty of the recipe"), mcp.Required()),
	)
	searchRecipesTool := mcp.NewTool("search_paprika_recipes",
		mcp.WithDescription("Search recipes from the Paprika 3 app across all fields. Reads directly from Paprika's local database."),
		mcp.WithString("query", mcp.Description("Search query to match against recipe fields"), mcp.DefaultString("")),
		mcp.WithString("search_in", mcp.Description("Optional: Comma-separated list of fields to search in (name,ingredients,directions,description,notes). Default searches all fields."), mcp.DefaultString("all")),
		mcp.WithNumber("min_rating", mcp.Description("Optional: Minimum rating (1-5 stars). Only recipes with this rating or higher will be returned."), mcp.DefaultNumber(0)),
		mcp.WithNumber("limit", mcp.Description("Optional: Maximum number of recipes to return (0 = no limit)"), mcp.DefaultNumber(0)),
		mcp.WithNumber("offset", mcp.Description("Optional: Number of recipes to skip (for pagination)"), mcp.DefaultNumber(0)),
	)
	getMenuTool := mcp.NewTool("get_paprika_menu",
		mcp.WithDescription("Get meal plan menu items for a date range from Paprika 3."),
		mcp.WithString("start_date", mcp.Description("Start date in YYYY-MM-DD format"), mcp.Required()),
		mcp.WithString("end_date", mcp.Description("End date in YYYY-MM-DD format"), mcp.Required()),
	)
	getGroceryListTool := mcp.NewTool("get_paprika_grocery_list",
		mcp.WithDescription("Get grocery list items from Paprika 3."),
		mcp.WithBoolean("unpurchased_only", mcp.Description("Optional: Only show unpurchased items"), mcp.DefaultBool(true)),
	)
	s.server.AddTools(server.ServerTool{
		Tool:    createRecipeTool,
		Handler: s.createRecipe,
	}, server.ServerTool{
		Tool:    updateRecipeTool,
		Handler: s.updateRecipe,
	}, server.ServerTool{
		Tool:    searchRecipesTool,
		Handler: s.searchRecipes,
	}, server.ServerTool{
		Tool:    getMenuTool,
		Handler: s.getMenu,
	}, server.ServerTool{
		Tool:    getGroceryListTool,
		Handler: s.getGroceryList,
	})

	if err := server.ServeStdio(s.server); err != nil {
		s.logger.Error("Server error", "err", err)
	}
}

func (s *Server) updateResources() {
	s.addResources()

	ticker := time.NewTicker(1 * time.Minute)
	for range ticker.C {
		s.addResources()
	}
}

func (s *Server) addResources() {
	s.logger.Info("Updating recipe resources")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// List all recipes to expose them as resources
	recipes, err := s.paprika3.ListRecipes(ctx)
	if err != nil {
		s.logger.Error("failed to list paprika recipes", "err", err)
		return
	}

	if len(recipes.Result) >= 10 {
		s.logger.Info("adding recipes resources concurrently")
		s.addResourcesConcurrently(recipes)
		return
	}

	for _, r := range recipes.Result {
		if err := s.addRecipeResource(r.UID); err != nil {
			s.logger.Error("failed to add recipe as MCP resource", "err", err)
		}
	}
}

func (s *Server) addRecipeResource(uid string) error {
	start := time.Now()
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.GetRecipe(ctx, uid)
	if err != nil {
		return err
	}

	if recipe.InTrash {
		return nil
	}

	resourceContents := mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}

	s.server.AddResource(mcp.NewResource(fmt.Sprintf("paprika://recipes/%s", recipe.UID), recipe.Name, mcp.WithResourceDescription(recipe.ResourceDescription()), mcp.WithMIMEType("text/markdown")), func(ctx context.Context, request mcp.ReadResourceRequest) ([]mcp.ResourceContents, error) {
		return []mcp.ResourceContents{resourceContents}, nil
	})

	duration := time.Since(start)
	s.logger.Info("Added resource", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return nil
}

func (s *Server) addResourcesConcurrently(recipes *paprika.RecipeList) {
	buffer := make(chan struct{}, 10)

	for _, r := range recipes.Result {
		go func() (err error) {
			buffer <- struct{}{}
			defer func() {
				<-buffer
			}()

			defer func(err error) {
				if err != nil {
					s.logger.Error("failed to add recipe as MCP resource", "err", err)
				}
			}(err)

			return s.addRecipeResource(r.UID)
		}()
	}
}

func (s *Server) createRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	servings, _ := req.Params.Arguments["servings"].(string)
	prepTime, _ := req.Params.Arguments["prep_time"].(string)
	cookTime, _ := req.Params.Arguments["cook_time"].(string)
	description, _ := req.Params.Arguments["description"].(string)
	notes, _ := req.Params.Arguments["notes"].(string)
	difficulty, _ := req.Params.Arguments["difficulty"].(string)

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Created recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) updateRecipe(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()
	uid, ok := req.Params.Arguments["uid"].(string)
	if !ok || len(uid) == 0 {
		return nil, errors.New("uid is required")
	}
	name, ok := req.Params.Arguments["name"].(string)
	if !ok || len(name) == 0 {
		return nil, errors.New("name is required")
	}
	ingredients, ok := req.Params.Arguments["ingredients"].(string)
	if !ok || len(ingredients) == 0 {
		return nil, errors.New("ingredients are required")
	}
	directions, ok := req.Params.Arguments["directions"].(string)
	if !ok || len(directions) == 0 {
		return nil, errors.New("directions are required")
	}
	description, ok := req.Params.Arguments["description"].(string)
	if !ok {
		return nil, errors.New("description is required")
	}
	servings, ok := req.Params.Arguments["servings"].(string)
	if !ok {
		return nil, errors.New("servings is required")
	}
	prepTime, ok := req.Params.Arguments["prep_time"].(string)
	if !ok {
		return nil, errors.New("prepTime is required")
	}
	cookTime, ok := req.Params.Arguments["cook_time"].(string)
	if !ok {
		return nil, errors.New("cookTime is required")
	}
	notes, ok := req.Params.Arguments["notes"].(string)
	if !ok {
		return nil, errors.New("notes is required")
	}
	difficulty, ok := req.Params.Arguments["difficulty"].(string)
	if !ok {
		return nil, errors.New("difficulty is required")
	}

	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	recipe, err := s.paprika3.SaveRecipe(ctx, paprika.Recipe{
		UID:         uid,
		Name:        name,
		Ingredients: ingredients,
		Directions:  directions,
		Description: description,
		Servings:    servings,
		PrepTime:    prepTime,
		CookTime:    cookTime,
		Notes:       notes,
		Difficulty:  difficulty,
	})
	if err != nil {
		return nil, err
	}

	duration := time.Since(start)
	s.logger.Info("Updated recipe", "name", recipe.Name, "uid", recipe.UID, "duration", duration)

	return mcp.NewToolResultResource(recipe.Name, mcp.TextResourceContents{
		URI:      fmt.Sprintf("paprika://recipes/%s", recipe.UID),
		MIMEType: "text/markdown",
		Text:     recipe.ToMarkdown(),
	}), nil
}

func (s *Server) searchRecipes(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Parse parameters
	query := ""
	if q, ok := req.Params.Arguments["query"].(string); ok {
		query = q
	}

	searchIn := "all"
	if si, ok := req.Params.Arguments["search_in"].(string); ok {
		searchIn = si
	}

	minRating := 0
	if mr, ok := req.Params.Arguments["min_rating"].(float64); ok {
		minRating = int(mr)
	}

	limit := 0
	if l, ok := req.Params.Arguments["limit"].(float64); ok {
		limit = int(l)
	}

	offset := 0
	if o, ok := req.Params.Arguments["offset"].(float64); ok {
		offset = int(o)
	}

	// Search in database
	recipes, totalCount, err := s.db.SearchRecipes(query, searchIn, minRating, limit, offset)
	if err != nil {
		s.logger.Error("failed to search recipes in database", "error", err)
		return nil, fmt.Errorf("failed to search recipes: %w", err)
	}

	// Build markdown output
	var output string
	if query != "" {
		output += fmt.Sprintf("# Search Results for \"%s\" (%d recipes found)\n", query, totalCount)
		if searchIn != "all" {
			output += fmt.Sprintf("**Searched in:** %s\n", searchIn)
		}
	} else {
		output += fmt.Sprintf("# All Paprika Recipes (%d recipes", totalCount)
		if offset > 0 || limit > 0 {
			output += fmt.Sprintf(", showing %d-%d", offset+1, offset+len(recipes))
		}
		output += ")\n"
	}

	output += "\n**Source:** Paprika Local Database\n"

	if minRating > 0 {
		stars := strings.Repeat("⭐", minRating)
		output += fmt.Sprintf("**Min Rating:** %s (%d+)\n", stars, minRating)
	}
	output += "\n"

	for _, recipe := range recipes {
		output += "---\n\n"
		output += recipe.ToMarkdown()
	}

	duration := time.Since(start)
	s.logger.Info("Searched recipes", "query", query, "fields", searchIn, "returned", len(recipes), "total", totalCount, "duration", duration)

	return mcp.NewToolResultText(output), nil
}

func (s *Server) getMenu(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Parse parameters
	startDate, _ := req.Params.Arguments["start_date"].(string)
	endDate, _ := req.Params.Arguments["end_date"].(string)

	items, err := s.db.GetMenuItems(startDate, endDate)
	if err != nil {
		return nil, fmt.Errorf("failed to get menu items: %w", err)
	}

	var output string
	output += fmt.Sprintf("# Meal Plan: %s to %s\n\n", startDate, endDate)
	output += fmt.Sprintf("**Total items:** %d\n\n", len(items))

	currentDate := ""
	for _, item := range items {
		date := item["date"].(string)
		if date != currentDate {
			currentDate = date
			output += fmt.Sprintf("## %s\n\n", date)
		}

		// Get meal type name from type_uid (could enhance this with a lookup table)
		mealType := "Meal"
		if typeUID, ok := item["type_uid"].(string); ok && typeUID != "" {
			// For now, just use the type_uid or default
			mealType = "Meal"
		}

		output += fmt.Sprintf("- **%s**: %s\n", mealType, item["name"].(string))
		if recipeUID := item["recipe_uid"].(string); recipeUID != "" {
			output += fmt.Sprintf("  - Recipe UID: %s\n", recipeUID)
		}
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved menu items", "count", len(items), "duration", duration)

	return mcp.NewToolResultText(output), nil
}

func (s *Server) getGroceryList(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	start := time.Now()

	// Parse parameters
	unpurchasedOnly := true
	if uo, ok := req.Params.Arguments["unpurchased_only"].(bool); ok {
		unpurchasedOnly = uo
	}

	items, err := s.db.GetGroceryItems(!unpurchasedOnly)
	if err != nil {
		return nil, fmt.Errorf("failed to get grocery items: %w", err)
	}

	var output string
	output += "# Grocery List\n\n"
	output += fmt.Sprintf("**Total items:** %d\n\n", len(items))

	currentAisle := ""
	for _, item := range items {
		aisle := item["aisle"].(string)
		if aisle != currentAisle {
			currentAisle = aisle
			if aisle != "" {
				output += fmt.Sprintf("## %s\n\n", aisle)
			} else {
				output += "## Other Items\n\n"
			}
		}

		checkbox := "☐"
		if item["purchased"].(bool) {
			checkbox = "☑"
		}

		name := item["name"].(string)
		quantity := item["quantity"].(string)

		if quantity != "" {
			output += fmt.Sprintf("%s **%s** - %s\n", checkbox, name, quantity)
		} else {
			output += fmt.Sprintf("%s **%s**\n", checkbox, name)
		}

		if recipe := item["recipe"].(string); recipe != "" {
			output += fmt.Sprintf("  - For: %s\n", recipe)
		}
	}

	duration := time.Since(start)
	s.logger.Info("Retrieved grocery items", "count", len(items), "duration", duration)

	return mcp.NewToolResultText(output), nil
}

// contains performs a case-insensitive substring match
func contains(s, substr string) bool {
	s, substr = toLower(s), toLower(substr)
	return len(s) >= len(substr) && (s == substr || indexOfSubstr(s, substr) >= 0)
}

func toLower(s string) string {
	result := make([]rune, len(s))
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			result[i] = r + 32
		} else {
			result[i] = r
		}
	}
	return string(result)
}

func indexOfSubstr(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
